import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timezone
from typing import List
from src.scrapers.base import JobPost
from src.profile import profile


class EmailNotifier:
    def __init__(self, from_addr: str, password: str, to_addr: str,
                 smtp_server: str = "smtp.gmail.com", smtp_port: int = 587):
        self.from_addr = from_addr
        self.password = password
        self.to_addr = to_addr
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port

    def send_jobs_report(self, jobs: List[JobPost]) -> bool:
        if not jobs:
            return self._send_empty_report()
        return self._send_report(jobs)

    def _build_html(self, jobs: List[JobPost]) -> str:
        items = ""
        for j in jobs:
            score_pct = int(j.match_score * 100)
            items += f"""
            <div style="border:1px solid #ddd;border-radius:8px;padding:16px;margin:12px 0">
                <h3 style="margin:0 0 4px 0">{j.title}</h3>
                <div style="color:#666;margin-bottom:8px">
                    {j.company} &bull; {j.source} &bull; Match: {score_pct}%
                </div>
                <div style="color:#888;font-size:0.9em;margin-bottom:8px">
                    {j.location} &bull; {j.posted_date.strftime('%Y-%m-%d') if j.posted_date else 'Recently'}
                </div>
                <p style="margin:8px 0">{j.description[:300]}{'...' if len(j.description) > 300 else ''}</p>
                <div style="margin-top:8px">
                    <a href="{j.url}" style="background:#0077B5;color:white;padding:8px 16px;border-radius:4px;text-decoration:none;display:inline-block">Apply</a>
                </div>
            </div>
            """

        return f"""
        <html>
        <head><meta charset="utf-8"></head>
        <body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px">
            <h1 style="color:#333">📋 Jobs Found for {profile.name}</h1>
            <p style="color:#666">{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</p>
            <p>Found <strong>{len(jobs)}</strong> matching jobs today.</p>
            {items}
            <hr style="margin-top:24px">
            <p style="color:#999;font-size:0.85em">
                Generated by Job Scraper Bot | Profile: {profile.title} | English: {profile.english_level}
            </p>
        </body>
        </html>
        """

    def _build_text(self, jobs: List[JobPost]) -> str:
        lines = [
            f"Job Report for {profile.name}",
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            f"Found {len(jobs)} matching jobs",
            "-" * 50,
        ]
        for j in jobs:
            score_pct = int(j.match_score * 100)
            lines.extend([
                f"\n★ {j.title}",
                f"  {j.company} | {j.source} | Match: {score_pct}%",
                f"  {j.location}",
                f"  {j.url}",
                f"  {j.description[:200]}...",
            ])
        return "\n".join(lines)

    def _send_report(self, jobs: List[JobPost]) -> bool:
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = f"📋 Job Bot Report - {len(jobs)} new matches found"
            msg["From"] = self.from_addr
            msg["To"] = self.to_addr
            msg.attach(MIMEText(self._build_text(jobs), "plain"))
            msg.attach(MIMEText(self._build_html(jobs), "html"))
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.from_addr, self.password)
                server.send_message(msg)
            return True
        except Exception as e:
            print(f"Email error: {e}")
            return False

    def _send_empty_report(self) -> bool:
        try:
            msg = MIMEText("No new matching jobs found today.")
            msg["Subject"] = "Job Bot Report - No matches today"
            msg["From"] = self.from_addr
            msg["To"] = self.to_addr
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.from_addr, self.password)
                server.send_message(msg)
            return True
        except Exception:
            return False
